FROM alpine:3.12.0 as base

RUN apk add --update --no-cache \
    bash \
    coreutils \
    curl \
    git \
    make \
    nginx \
    php7-fpm \
    php7-apcu \
    php7-ctype \
    php7-curl \
    php7-dom \
    php7-gd \
    php7-iconv \
    php7-imagick \
    php7-json \
    php7-intl \
    php7-mcrypt \
    php7-fileinfo \
    php7-mbstring \
    php7-opcache \
    php7-openssl \
    php7-pdo \
    php7-pdo_mysql \
    php7-pdo_pgsql \
    php7-pdo_sqlite \
    php7-posix \
    php7-mysqli \
    php7-xml \
    php7-phar \
    php7-tokenizer \
    php7-session \
    php7-simplexml \
    php7-xdebug \
    php7-zip \
    php7-xmlwriter \
    supervisor \
    yarn

RUN echo "$(curl -sS https://composer.github.io/installer.sig) -" > composer-setup.php.sig \
    && curl -sS https://getcomposer.org/installer | tee composer-setup.php | sha384sum -c composer-setup.php.sig \
    && php composer-setup.php && rm composer-setup.php* \
    && chmod +x composer.phar && mv composer.phar /usr/bin/composer
  
RUN curl -sS https://get.symfony.com/cli/installer | bash
RUN mv /root/.symfony/bin/symfony /usr/local/bin/symfony

# ---

RUN rm /etc/nginx/conf.d/default.conf
COPY .docker/nginx.conf /etc/nginx/nginx.conf
RUN echo "upstream php-upstream { server 127.0.0.1:9001; }" > /etc/nginx/conf.d/upstream.conf

RUN rm /etc/php7/php-fpm.d/www.conf
COPY .docker/php-fpm.conf /etc/php7/php-fpm.d/php-fpm.conf
COPY .docker/symfony.dev.ini /etc/php7/conf.d/symfony.ini
COPY .docker/symfony.dev.ini /etc/php7/cli/conf.d/symfony.ini
COPY .docker/xdebug.ini /etc/php7/conf.d/xdebug.ini

COPY .docker/supervisord.conf /etc/supervisord.conf

RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log \
    && ln -sf /dev/stderr /var/log/php7/error.log

# ---

WORKDIR /symfony

COPY composer.json .
COPY composer.lock .

COPY symfony.lock .

RUN composer install --no-interaction --no-plugins --no-progress --no-scripts --no-suggest

# ----

COPY composer.json package.json* ./
COPY composer.json yarn.lock* ./

COPY composer.json webpack.config.js* ./
COPY composer.json assets* ./assets/

RUN if [ -f webpack.config.js ]; then \
      yarn; \
      yarn encore dev; \
    fi

# ---

COPY .docker/entrypoint.sh /entrypoint.sh
COPY .docker/entrypoint.test.sh /entrypoint.test.sh

RUN chmod +x /entrypoint.sh /entrypoint.test.sh

COPY . .

RUN addgroup symfony && adduser -D -G symfony symfony && \
    chown -R symfony:symfony /symfony /var/lib/nginx /etc/nginx

USER symfony

EXPOSE 9000
ENTRYPOINT ["/entrypoint.sh"]